server:
  port: 3000

spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/petry1
    username: sa
    password: 522208

  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true

    hibernate:
      ddl-auto: create

    show-sql: true

  profiles:
    include: jwt

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hibernate:
        SQL: debug
        type: trace


