server:
  port: 3000

spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/?user=root
    #username: root
    #password: 1234

    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/petry1
    username: sa
    password: 522208

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true

    hibernate:
      ddl-auto: create

    show-sql: true

  profiles:
    group:
      "dev-profile": "dev,jwt"
      "prod-profile": "prod,jwt"
    include: jwt

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hibernate:
        SQL: debug
        type: trace


file:
  dir: D:\petry_img